// The code below is generated by Gemini AI
package com.example.shop;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class DiscountServiceTest {

    private DiscountService discountService;

    @Before
    public void setUp() {
        discountService = new DiscountService();
    }

    @Test
    public void testApplyDiscount_NoCode_ReturnsOriginalPrice() {
        assertEquals(100.0, discountService.applyDiscount(100.0, null), 0.001);
        assertEquals(100.0, discountService.applyDiscount(100.0, "  "), 0.001);
    }

    @Test
    public void testApplyDiscount_StudentCode_Applies10Percent() {
        double result = discountService.applyDiscount(100.0, "STUDENT10");
        assertEquals(90.0, result, 0.001);
    }

    @Test
    public void testApplyDiscount_BlackFridayCode_Applies30Percent() {
        double result = discountService.applyDiscount(100.0, "BLACKFRIDAY");
        assertEquals(70.0, result, 0.001);
    }

    @Test
    public void testApplyDiscount_UnknownCode_ReturnsOriginalPrice() {
        double result = discountService.applyDiscount(100.0, "HELLO20");
        assertEquals(100.0, result, 0.001);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testApplyDiscount_InvalidCode_ThrowsException() {
        discountService.applyDiscount(100.0, "INVALID");
    }
}