// the code below is generated by Gemini
package com.example.shop;

import org.junit.Test;
import static org.junit.Assert.*;

public class OrderItemTest {

    @Test
    public void testGetTotalPrice_CalculatesCorrectly() {
        OrderItem item = new OrderItem("Widget", 3, 10.50);
        assertEquals(31.50, item.getTotalPrice(), 0.001);
    }

    @Test
    public void testConstructor_ValidInputs_SetsFields() {
        OrderItem item = new OrderItem("Gadget", 1, 5.0);
        assertEquals(1, item.getQuantity());
    }

    @Test(expected = IllegalArgumentException.class)
    public void testConstructor_ZeroQuantity_ThrowsException() {
        new OrderItem("Error", 0, 10.0);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testConstructor_NegativeQuantity_ThrowsException() {
        new OrderItem("Error", -5, 10.0);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testConstructor_NegativePrice_ThrowsException() {
        new OrderItem("Error", 2, -1.0);
    }

    @Test
    public void testConstructor_ZeroPrice_IsAllowed() {
        OrderItem freebie = new OrderItem("Freebie", 1, 0.0);
        assertEquals(0.0, freebie.getTotalPrice(), 0.0);
    }
}