//the code below is generated by Gemini
//package com.example.shop;
//
//import org.junit.Before;
//import org.junit.Test;
//import static org.junit.Assert.*;
//
//public class OrderServiceTest {
//
//    private OrderService orderService;
//    private Order order;
//
//    @Before
//    public void setUp() {
//        orderService = new OrderService();
//        order = new Order();
//        // Adding items so pricingService has values to calculate
//        order.addItem(new OrderItem("Book", 1, 10.0)); 
//    }
//
//    @Test
//    public void testProcessOrder_ValidPayment_SetsStatusToPaid() {
//        double total = orderService.processOrder(order, "STUDENT10", "CREDIT_CARD");
//        
//        assertEquals(OrderStatus.PAID, order.getStatus());
//        assertTrue(total > 0);
//    }
//
//    @Test
//    public void testProcessOrder_InvalidPayment_CancelsOrder() {
//        double total = orderService.processOrder(order, "STUDENT10", "INVALID_METHOD");
//        
//        assertEquals(OrderStatus.CANCELLED, order.getStatus());
//        assertEquals(0, total, 0.001);
//    }
//
//    @Test
//    public void testProcessOrder_WithDiscount_CalculatesCorrectTotal() {
//        // subtotal = 10.0, discount = 10% (9.0), plus tax (assuming PricingService logic)
//        double total = orderService.processOrder(order, "STUDENT10", "DEBIT");
//        
//        // Asserting logic based on combined DiscountService and PricingService
//        assertTrue(total > 0);
//    }
//
//    @Test
//    public void testProcessOrder_NoDiscount_WorksCorrectly() {
//        double total = orderService.processOrder(order, null, "CASH");
//        
//        assertEquals(OrderStatus.PAID, order.getStatus());
//    }
//}


// Second attempt 
// here I noticed  Gemini does not have an idea about the services/classes we want to mock
// so I modified the payment types
// however the first unit test did fail and after spending some time debugging I found the mocked values passed to
// OrderService are being overridden for example in the unit test we have when(pricingService.calculateSubtotal(order)).thenReturn(100.0);
// but when debugging the value in the class method process_order double subtotal = pricingService.calculateSubtotal(order) was 0
// I reprompted Gemini, ccheck the code after in attempt three
// also a note I kept the discount code as generated by Gemini which are not the expected ones because it does not really matter the discount code value because we are mocking the return value to be fixed 
//package com.example.shop;
//
//import org.junit.Before;
//import org.junit.Test;
//import org.junit.runner.RunWith;
//import org.mockito.InjectMocks;
//import org.mockito.Mock;
//import org.mockito.junit.MockitoJUnitRunner;
//
//import static org.junit.Assert.*;
//import static org.mockito.Mockito.*;
//
//@RunWith(MockitoJUnitRunner.class)
//public class OrderServiceTest {
//
//    @Mock 
//    private PricingService pricingService;
//    @Mock 
//    private DiscountService discountService;
//    @Mock 
//    private PaymentValidator paymentValidator;
//
//    @InjectMocks
//    private OrderService orderService; // Mockito injects the mocks above into this instance
//
//    private Order order;
//
//    @Before
//    public void setUp() {
//        order = new Order();
//    }
//
//    @Test
//    public void testProcessOrder_Success() {
//        // Arrange
//        when(paymentValidator.isPaymentMethodValid("card")).thenReturn(true);
//        when(pricingService.calculateSubtotal(order)).thenReturn(100.0);
//        when(discountService.applyDiscount(100.0, "SAVE5")).thenReturn(95.0);
//        when(pricingService.calculateTax(95.0)).thenReturn(5.0);
////        System.out.print(pricingService.calculateTax(95.0));
//        // Act
//        double total = orderService.processOrder(order, "SAVE5", "card");
//        // Assert
//        assertEquals(100.0, total, 0.001);
//        assertEquals(OrderStatus.PAID, order.getStatus());
//    }
//
//    @Test
//    public void testProcessOrder_InvalidPayment() {
//        // Arrange
//        when(paymentValidator.isPaymentMethodValid("crypto")).thenReturn(false);
//
//        // Act
//        double total = orderService.processOrder(order, "NONE", "crypto");
//
//        // Assert
//        assertEquals(0.0, total, 0.0);
//        assertEquals(OrderStatus.CANCELLED, order.getStatus());
//        verifyNoInteractions(pricingService, discountService);
//    }
//}

// attempt 3, code generated by Gemini 
// I just modified the payment method name to be CARD
//package com.example.shop;
//
//import org.junit.Before;
//import org.junit.Test;
//import java.lang.reflect.Field;
//import static org.junit.Assert.*;
//import static org.mockito.Mockito.*;
//
//public class OrderServiceTest {
//
//    private OrderService orderService;
//    private PricingService pricingService;
//    private DiscountService discountService;
//    private PaymentValidator paymentValidator;
//
//    @Before
//    public void setUp() throws Exception {
//        orderService = new OrderService();
//        
//        // Create mocks
//        pricingService = mock(PricingService.class);
//        discountService = mock(DiscountService.class);
//        paymentValidator = mock(PaymentValidator.class);
//
//        // Force injection into private fields via reflection
//        setInternalState(orderService, "pricingService", pricingService);
//        setInternalState(orderService, "discountService", discountService);
//        setInternalState(orderService, "paymentValidator", paymentValidator);
//    }
//
//    // Helper to bypass "private final" restrictions
//    private void setInternalState(Object target, String fieldName, Object value) throws Exception {
//        Field field = target.getClass().getDeclaredField(fieldName);
//        field.setAccessible(true);
//        field.set(target, value);
//    }
//
//    @Test
//    public void testProcessOrder_ReturnsCorrectTotal() {
//        // Arrange
//        Order order = new Order();
//        when(paymentValidator.isPaymentMethodValid("CARD")).thenReturn(true);
//        when(pricingService.calculateSubtotal(order)).thenReturn(100.0);
//        when(discountService.applyDiscount(100.0, "SAVE10")).thenReturn(90.0);
//        when(pricingService.calculateTax(90.0)).thenReturn(9.0);
//
//        // Act
//        double result = orderService.processOrder(order, "SAVE10", "CARD");
//
//        // Assert
//        assertEquals(99.0, result, 0.001);
//        assertEquals(OrderStatus.PAID, order.getStatus());
//    }
//}

// forth attempt, again as above the code below is generated by Gemini 
package com.example.shop;
import org.junit.Before;
import org.junit.Test;
import java.lang.reflect.Field;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

public class OrderServiceTest {

    private OrderService orderService;
    private PricingService pricingService;
    private DiscountService discountService;
    private PaymentValidator paymentValidator;

    @Before
    public void setUp() throws Exception {
        orderService = new OrderService();
        
        // Create mocks
        pricingService = mock(PricingService.class);
        discountService = mock(DiscountService.class);
        paymentValidator = mock(PaymentValidator.class);

        // Force injection into private fields via reflection
        setInternalState(orderService, "pricingService", pricingService);
        setInternalState(orderService, "discountService", discountService);
        setInternalState(orderService, "paymentValidator", paymentValidator);
    }

    // Helper to bypass "private final" restrictions
    private void setInternalState(Object target, String fieldName, Object value) throws Exception {
        Field field = target.getClass().getDeclaredField(fieldName);
        field.setAccessible(true);
        field.set(target, value);
    }

    @Test
    public void testProcessOrder_ReturnsCorrectTotal() {
        // Arrange
        Order order = new Order();
        when(paymentValidator.isPaymentMethodValid("CARD")).thenReturn(true);
        when(pricingService.calculateSubtotal(order)).thenReturn(100.0);
        when(discountService.applyDiscount(100.0, "SAVE10")).thenReturn(90.0);
        when(pricingService.calculateTax(90.0)).thenReturn(9.0);

        // Act
        double result = orderService.processOrder(order, "SAVE10", "CARD");

        // Assert
        assertEquals(99.0, result, 0.001);
        assertEquals(OrderStatus.PAID, order.getStatus());
    }
    @Test
    public void testProcessOrder_InvalidPayment_ReturnsZeroAndCancels() throws Exception {
        // Arrange
        Order order = new Order();
        String badMethod = "INVALID_CARD";
        
        // Force the mock to return false
        when(paymentValidator.isPaymentMethodValid(badMethod)).thenReturn(false);

        // Act
        double result = orderService.processOrder(order, "ANY_CODE", badMethod);

        // Assert
        assertEquals(0.0, result, 0.0);
        assertEquals(OrderStatus.CANCELLED, order.getStatus());
        
        // Verify that pricing logic was NEVER touched
        verifyNoInteractions(pricingService, discountService);
    }

    @Test
    public void testProcessOrder_NoDiscountCode_CalculatesFullPrice() throws Exception {
        // Arrange
        Order order = new Order();
        when(paymentValidator.isPaymentMethodValid("CARD")).thenReturn(true);
        when(pricingService.calculateSubtotal(order)).thenReturn(100.0);
        
        // Mocking the case where no discount is applied (returns original subtotal)
        when(discountService.applyDiscount(100.0, null)).thenReturn(100.0);
        when(pricingService.calculateTax(100.0)).thenReturn(10.0);

        // Act
        double result = orderService.processOrder(order, null, "CARD");

        // Assert
        assertEquals(110.0, result, 0.001);
        assertEquals(OrderStatus.PAID, order.getStatus());
        
        // Verify the sequence of calls
        verify(pricingService).calculateSubtotal(order);
        verify(discountService).applyDiscount(100.0, null);
    }
}
