// code below generated by Gemini
// coverage is 100% first attempt
package com.example.shop;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class PaymentValidatorTest {

    private PaymentValidator validator;

    @Before
    public void setUp() {
        validator = new PaymentValidator();
    }

    @Test
    public void testIsPaymentMethodValid_ValidMethods_ReturnsTrue() {
        assertTrue(validator.isPaymentMethodValid("card"));
        assertTrue(validator.isPaymentMethodValid("PAYPAL")); // Check case insensitivity
    }

    @Test
    public void testIsPaymentMethodValid_Crypto_ReturnsFalse() {
        assertFalse(validator.isPaymentMethodValid("crypto"));
    }

    @Test
    public void testIsPaymentMethodValid_Null_ReturnsFalse() {
        assertFalse(validator.isPaymentMethodValid(null));
    }

    @Test(expected = UnsupportedOperationException.class)
    public void testIsPaymentMethodValid_UnknownMethod_ThrowsException() {
        validator.isPaymentMethodValid("gold_bars");
    }
}