// code below generated by Gemini
// coverage is 100% first attempt
package com.example.shop;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class PricingServiceTest {

    private PricingService pricingService;

    @Before
    public void setUp() {
        pricingService = new PricingService();
    }

    @Test
    public void testCalculateSubtotal_MultipleItems_ReturnsSum() {
        Order order = new Order();
        order.addItem(new OrderItem("Item 1", 2, 10.0)); // 20.0
        order.addItem(new OrderItem("Item 2", 1, 5.5));  // 5.5
        
        assertEquals(25.5, pricingService.calculateSubtotal(order), 0.001);
    }

    @Test
    public void testCalculateSubtotal_EmptyOrder_ReturnsZero() {
        Order order = new Order();
        assertEquals(0.0, pricingService.calculateSubtotal(order), 0.0);
    }

    @Test
    public void testCalculateTax_NormalAmount_Applies20Percent() {
        double tax = pricingService.calculateTax(100.0);
        assertEquals(20.0, tax, 0.001);
    }

    @Test
    public void testCalculateTax_ZeroSubtotal_ReturnsZero() {
        assertEquals(0.0, pricingService.calculateTax(0.0), 0.0);
    }

    @Test(expected = IllegalArgumentException.class)
    public void testCalculateTax_NegativeSubtotal_ThrowsException() {
        pricingService.calculateTax(-10.0);
    }
}